// Code generated by "stringer -type=Type -output ./type_string.go"; DO NOT EDIT.

package meta

import "strconv"

const _Type_name = "CommentTypeWhiteSpaceTypeTokenType"

var _Type_index = [...]uint8{0, 11, 25, 34}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
