// Code generated by "stringer -type=EdgeType -trimprefix=EdgeType -output ./edgetype_string.go"; DO NOT EDIT.

package ast

import "strconv"

const _EdgeType_name = "NilExprVarTypeVarDefaultValueArgumentsStmtsPartsCondStmtElseIfElseTypesModifiersConstsMethodNameParamsReturnTypeClassNameArgumentListExtendsImplementsConstantNameExprsInitLoopKeyFunctionNameVarsLabelUseTypePrefixUseListInterfaceNameLabelNameNamespaceNamePropertiesCaseListTraitMethodRefModifierAliasInsteadofTraitsTraitAdaptationListTraitNameCatchesFinallyUsesUseCasesAdaptationsInterfaceNamesLeftRightDimValItemsClassClosureUseConstantFunctionPropertyCallIfTrueIfFalseVarName"

var _EdgeType_index = [...]uint16{0, 3, 7, 14, 17, 29, 38, 43, 48, 52, 56, 62, 66, 71, 80, 86, 96, 102, 112, 121, 133, 140, 150, 162, 167, 171, 175, 178, 190, 194, 199, 206, 212, 219, 232, 241, 254, 264, 272, 277, 283, 286, 294, 299, 308, 314, 333, 342, 349, 356, 360, 363, 368, 379, 393, 397, 402, 405, 408, 413, 418, 428, 436, 444, 452, 456, 462, 469, 476}

func (i EdgeType) String() string {
	if i >= EdgeType(len(_EdgeType_index)-1) {
		return "EdgeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EdgeType_name[_EdgeType_index[i]:_EdgeType_index[i+1]]
}
