// Code generated by "stringer -type=NodeFlag -trimprefix=NodeFlag -output ./nodeflag_string.go"; DO NOT EDIT.

package ast

import "strconv"

const (
	_NodeFlag_name_0 = "RefVariadic"
	_NodeFlag_name_1 = "Static"
	_NodeFlag_name_2 = "AltSyntax"
)

var (
	_NodeFlag_index_0 = [...]uint8{0, 3, 11}
)

func (i NodeFlag) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _NodeFlag_name_0[_NodeFlag_index_0[i]:_NodeFlag_index_0[i+1]]
	case i == 4:
		return _NodeFlag_name_1
	case i == 8:
		return _NodeFlag_name_2
	default:
		return "NodeFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
