// Code generated by "stringer -type=TokenType -trimprefix=TokenType -output ./tokentype_string.go"; DO NOT EDIT.

package ast

import "strconv"

const _TokenType_name = "CommentWhitespaceToken"

var _TokenType_index = [...]uint8{0, 7, 17, 22}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
