// Code generated by "stringer -type=Position -output ./position_string.go"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Start-0]
	_ = x[End-1]
	_ = x[SemiColon-2]
	_ = x[AltEnd-3]
	_ = x[Ampersand-4]
	_ = x[Name-5]
	_ = x[Key-6]
	_ = x[Var-7]
	_ = x[ReturnType-8]
	_ = x[CaseSeparator-9]
	_ = x[LexicalVars-10]
	_ = x[Params-11]
	_ = x[Ref-12]
	_ = x[Cast-13]
	_ = x[Expr-14]
	_ = x[InitExpr-15]
	_ = x[CondExpr-16]
	_ = x[IncExpr-17]
	_ = x[True-18]
	_ = x[Cond-19]
	_ = x[Namespace-20]
	_ = x[Static-21]
	_ = x[Class-22]
	_ = x[Use-23]
	_ = x[While-24]
	_ = x[For-25]
	_ = x[Switch-26]
	_ = x[Foreach-27]
	_ = x[Declare-28]
	_ = x[Label-29]
	_ = x[Finally-30]
	_ = x[List-31]
	_ = x[Default-32]
	_ = x[If-33]
	_ = x[ElseIf-34]
	_ = x[Else-35]
	_ = x[Function-36]
	_ = x[Alias-37]
	_ = x[Equal-38]
	_ = x[Exit-39]
	_ = x[Array-40]
	_ = x[Isset-41]
	_ = x[Empty-42]
	_ = x[Eval-43]
	_ = x[Echo-44]
	_ = x[Try-45]
	_ = x[Catch-46]
	_ = x[Unset-47]
	_ = x[Stmts-48]
	_ = x[VarList-49]
	_ = x[ConstList-50]
	_ = x[NameList-51]
	_ = x[ParamList-52]
	_ = x[ModifierList-53]
	_ = x[ArrayPairList-54]
	_ = x[CaseListStart-55]
	_ = x[CaseListEnd-56]
	_ = x[ArgumentList-57]
	_ = x[PropertyList-58]
	_ = x[ParameterList-59]
	_ = x[AdaptationList-60]
	_ = x[LexicalVarList-61]
	_ = x[OpenParenthesisToken-62]
	_ = x[CloseParenthesisToken-63]
}

const _Position_name = "StartEndSemiColonAltEndAmpersandNameKeyVarReturnTypeCaseSeparatorLexicalVarsParamsRefCastExprInitExprCondExprIncExprTrueCondNamespaceStaticClassUseWhileForSwitchForeachDeclareLabelFinallyListDefaultIfElseIfElseFunctionAliasEqualExitArrayIssetEmptyEvalEchoTryCatchUnsetStmtsVarListConstListNameListParamListModifierListArrayPairListCaseListStartCaseListEndArgumentListPropertyListParameterListAdaptationListLexicalVarListOpenParenthesisTokenCloseParenthesisToken"

var _Position_index = [...]uint16{0, 5, 8, 17, 23, 32, 36, 39, 42, 52, 65, 76, 82, 85, 89, 93, 101, 109, 116, 120, 124, 133, 139, 144, 147, 152, 155, 161, 168, 175, 180, 187, 191, 198, 200, 206, 210, 218, 223, 228, 232, 237, 242, 247, 251, 255, 258, 263, 268, 273, 280, 289, 297, 306, 318, 331, 344, 355, 367, 379, 392, 406, 420, 440, 461}

func (i Position) String() string {
	if i < 0 || i >= Position(len(_Position_index)-1) {
		return "Position(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Position_name[_Position_index[i]:_Position_index[i+1]]
}
